spring: 
  profiles:
    active: dev   
  datasource: 
    url: jdbc:mysql://119.29.22.157:3306/patpat?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: pat
    password: xmu123
#    url:jdbc:mysql://localhost:3306/patpat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual    #包括这条和一下三条用来测试连接是否有效，有效连接才会给用户使用。
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 文献1：https://www.cnblogs.com/wuyun-blog/p/5679073.html
    # 文献2：https://blog.csdn.net/shenzhennba/article/details/20855149
    #thymeleaf文献：http://blog.csdn.net/u012706811/article/details/52185345
  thymeleaf:
    cache: false  #此处如果是开发时要关闭缓存，否则页面会总是被缓存
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    mode: LEGACYHTML5

mybatis:
  mapper-locations: classpath:com/etc/mapper/*.xml
  typeAliasesPackage: com.etc.entity
  
