package com.etc.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String adminname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String adminpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPwd
     *
     * @return the value of admin.adminPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAdminpwd() {
        return adminpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPwd
     *
     * @param adminpwd the value for admin.adminPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAdminpwd(String adminpwd) {
        this.adminpwd = adminpwd;
    }
}