package com.etc.entity;

import java.util.Date;

public class App {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String appname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appIcon
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String appicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appDownloads
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String appdownloads;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Date appdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String apptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appLink
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String applink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Float appscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.appDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String appdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appId
     *
     * @return the value of app.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appId
     *
     * @param appid the value for app.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appName
     *
     * @return the value of app.appName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAppname() {
        return appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appName
     *
     * @param appname the value for app.appName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppname(String appname) {
        this.appname = appname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appIcon
     *
     * @return the value of app.appIcon
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAppicon() {
        return appicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appIcon
     *
     * @param appicon the value for app.appIcon
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppicon(String appicon) {
        this.appicon = appicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appDownloads
     *
     * @return the value of app.appDownloads
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAppdownloads() {
        return appdownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appDownloads
     *
     * @param appdownloads the value for app.appDownloads
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppdownloads(String appdownloads) {
        this.appdownloads = appdownloads;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appDate
     *
     * @return the value of app.appDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Date getAppdate() {
        return appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appDate
     *
     * @param appdate the value for app.appDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppdate(Date appdate) {
        this.appdate = appdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appType
     *
     * @return the value of app.appType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appType
     *
     * @param apptype the value for app.appType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setApptype(String apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appLink
     *
     * @return the value of app.appLink
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getApplink() {
        return applink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appLink
     *
     * @param applink the value for app.appLink
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setApplink(String applink) {
        this.applink = applink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appScore
     *
     * @return the value of app.appScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Float getAppscore() {
        return appscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appScore
     *
     * @param appscore the value for app.appScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppscore(Float appscore) {
        this.appscore = appscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.appDetail
     *
     * @return the value of app.appDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getAppdetail() {
        return appdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.appDetail
     *
     * @param appdetail the value for app.appDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppdetail(String appdetail) {
        this.appdetail = appdetail;
    }
}