package com.etc.entity;

public class AppFollow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_follow.followId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer followid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_follow.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_follow.followappId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer followappid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_follow.followId
     *
     * @return the value of app_follow.followId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getFollowid() {
        return followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_follow.followId
     *
     * @param followid the value for app_follow.followId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setFollowid(Integer followid) {
        this.followid = followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_follow.userId
     *
     * @return the value of app_follow.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_follow.userId
     *
     * @param userid the value for app_follow.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_follow.followappId
     *
     * @return the value of app_follow.followappId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getFollowappid() {
        return followappid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_follow.followappId
     *
     * @param followappid the value for app_follow.followappId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setFollowappid(Integer followappid) {
        this.followappid = followappid;
    }
}