package com.etc.entity;

public class AppLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_label.labelId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer labelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_label.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_label.labelName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String labelname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_label.labelId
     *
     * @return the value of app_label.labelId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getLabelid() {
        return labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_label.labelId
     *
     * @param labelid the value for app_label.labelId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setLabelid(Integer labelid) {
        this.labelid = labelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_label.appId
     *
     * @return the value of app_label.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_label.appId
     *
     * @param appid the value for app_label.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_label.labelName
     *
     * @return the value of app_label.labelName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getLabelname() {
        return labelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_label.labelName
     *
     * @param labelname the value for app_label.labelName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setLabelname(String labelname) {
        this.labelname = labelname;
    }
}