package com.etc.entity;

public class Aprioriresult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AprioriResult.AprioriId
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    private Integer aprioriid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AprioriResult.frequent
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    private String frequent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AprioriResult.support
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    private Double support;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AprioriResult.times
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AprioriResult.size
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    private Integer size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AprioriResult.AprioriId
     *
     * @return the value of AprioriResult.AprioriId
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public Integer getAprioriid() {
        return aprioriid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AprioriResult.AprioriId
     *
     * @param aprioriid the value for AprioriResult.AprioriId
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public void setAprioriid(Integer aprioriid) {
        this.aprioriid = aprioriid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AprioriResult.frequent
     *
     * @return the value of AprioriResult.frequent
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public String getFrequent() {
        return frequent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AprioriResult.frequent
     *
     * @param frequent the value for AprioriResult.frequent
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public void setFrequent(String frequent) {
        this.frequent = frequent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AprioriResult.support
     *
     * @return the value of AprioriResult.support
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public Double getSupport() {
        return support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AprioriResult.support
     *
     * @param support the value for AprioriResult.support
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public void setSupport(Double support) {
        this.support = support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AprioriResult.times
     *
     * @return the value of AprioriResult.times
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AprioriResult.times
     *
     * @param times the value for AprioriResult.times
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AprioriResult.size
     *
     * @return the value of AprioriResult.size
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AprioriResult.size
     *
     * @param size the value for AprioriResult.size
     *
     * @mbggenerated Mon Jul 23 15:55:20 CST 2018
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    public Aprioriresult(String frequent, double support, int times, int size) {
        super();
        this.frequent = frequent;
        this.support = support;
        this.times = times;
        this.size = size;
    }
    public Aprioriresult() {
        super();
    }
}