package com.etc.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.lastId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer lastid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer commentscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Date commentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentLike
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer commentlike;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String commentdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentId
     *
     * @return the value of comment.commentId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentId
     *
     * @param commentid the value for comment.commentId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.lastId
     *
     * @return the value of comment.lastId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getLastid() {
        return lastid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.lastId
     *
     * @param lastid the value for comment.lastId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setLastid(Integer lastid) {
        this.lastid = lastid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.userId
     *
     * @return the value of comment.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.userId
     *
     * @param userid the value for comment.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.appId
     *
     * @return the value of comment.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.appId
     *
     * @param appid the value for comment.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentScore
     *
     * @return the value of comment.commentScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getCommentscore() {
        return commentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentScore
     *
     * @param commentscore the value for comment.commentScore
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setCommentscore(Integer commentscore) {
        this.commentscore = commentscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentDate
     *
     * @return the value of comment.commentDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentDate
     *
     * @param commentdate the value for comment.commentDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentLike
     *
     * @return the value of comment.commentLike
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getCommentlike() {
        return commentlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentLike
     *
     * @param commentlike the value for comment.commentLike
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setCommentlike(Integer commentlike) {
        this.commentlike = commentlike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentDetail
     *
     * @return the value of comment.commentDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getCommentdetail() {
        return commentdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentDetail
     *
     * @param commentdetail the value for comment.commentDetail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setCommentdetail(String commentdetail) {
        this.commentdetail = commentdetail;
    }
}