package com.etc.entity;

public class Great {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column great.id
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column great.userId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column great.commentId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    private Integer commentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column great.id
     *
     * @return the value of great.id
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column great.id
     *
     * @param id the value for great.id
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column great.userId
     *
     * @return the value of great.userId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column great.userId
     *
     * @param userid the value for great.userId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column great.commentId
     *
     * @return the value of great.commentId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column great.commentId
     *
     * @param commentid the value for great.commentId
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }
}