package com.etc.entity;

import java.util.Date;

public class UserActivity {

    /**
     * 行为：
     * 1:access
     * 2:follow
     * 3:unfollow
     * 4:comment
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.activityId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.activityType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer activitytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_activity.activityDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Date activitydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.activityId
     *
     * @return the value of user_activity.activityId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.activityId
     *
     * @param activityid the value for user_activity.activityId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.userId
     *
     * @return the value of user_activity.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.userId
     *
     * @param userid the value for user_activity.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.appId
     *
     * @return the value of user_activity.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.appId
     *
     * @param appid the value for user_activity.appId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setAppid(Integer appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.activityType
     *
     * @return the value of user_activity.activityType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getActivitytype() {
        return activitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.activityType
     *
     * @param activitytype the value for user_activity.activityType
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setActivitytype(Integer activitytype) {
        this.activitytype = activitytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_activity.activityDate
     *
     * @return the value of user_activity.activityDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Date getActivitydate() {
        return activitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_activity.activityDate
     *
     * @param activitydate the value for user_activity.activityDate
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setActivitydate(Date activitydate) {
        this.activitydate = activitydate;
    }
}