package com.etc.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAvater
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String useravater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPhone
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String userphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEmail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userBirthday
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private Date userbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRegion
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String userregion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSex
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userHobby
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    private String userhobby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPwd
     *
     * @return the value of user.userPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPwd
     *
     * @param userpwd the value for user.userPwd
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAvater
     *
     * @return the value of user.userAvater
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUseravater() {
        return useravater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAvater
     *
     * @param useravater the value for user.userAvater
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUseravater(String useravater) {
        this.useravater = useravater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPhone
     *
     * @return the value of user.userPhone
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPhone
     *
     * @param userphone the value for user.userPhone
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEmail
     *
     * @return the value of user.userEmail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEmail
     *
     * @param useremail the value for user.userEmail
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userBirthday
     *
     * @return the value of user.userBirthday
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public Date getUserbirthday() {
        return userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userBirthday
     *
     * @param userbirthday the value for user.userBirthday
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserbirthday(Date userbirthday) {
        this.userbirthday = userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRegion
     *
     * @return the value of user.userRegion
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUserregion() {
        return userregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRegion
     *
     * @param userregion the value for user.userRegion
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserregion(String userregion) {
        this.userregion = userregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSex
     *
     * @return the value of user.userSex
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSex
     *
     * @param usersex the value for user.userSex
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userHobby
     *
     * @return the value of user.userHobby
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public String getUserhobby() {
        return userhobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userHobby
     *
     * @param userhobby the value for user.userHobby
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    public void setUserhobby(String userhobby) {
        this.userhobby = userhobby;
    }
}