package com.etc.dao;

import com.etc.entity.AppFollow;
import com.etc.entity.AppFollowExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface AppFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int countByExample(AppFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByExample(AppFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insert(AppFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insertSelective(AppFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    List<AppFollow> selectByExample(AppFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    AppFollow selectByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppFollow record, @Param("example") AppFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExample(@Param("record") AppFollow record, @Param("example") AppFollowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKeySelective(AppFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_follow
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKey(AppFollow record);
}