package com.etc.dao;

import com.etc.entity.AppLabel;
import com.etc.entity.AppLabelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int countByExample(AppLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByExample(AppLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insert(AppLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insertSelective(AppLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    List<AppLabel> selectByExample(AppLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    AppLabel selectByPrimaryKey(Integer labelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") AppLabel record, @Param("example") AppLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExample(@Param("record") AppLabel record, @Param("example") AppLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKeySelective(AppLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_label
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKey(AppLabel record);
}