package com.etc.dao;

import com.etc.entity.Great;
import com.etc.entity.GreatExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface GreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int countByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int deleteByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int insert(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int insertSelective(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    List<Great> selectByExample(GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    Great selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") Great record, @Param("example") GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int updateByExample(@Param("record") Great record, @Param("example") GreatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int updateByPrimaryKeySelective(Great record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table great
     *
     * @mbggenerated Mon Jul 23 15:45:26 CST 2018
     */
    int updateByPrimaryKey(Great record);
}