package com.etc.dao;

import com.etc.entity.UserActivity;
import com.etc.entity.UserActivityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface UserActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int countByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int deleteByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insert(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int insertSelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    List<UserActivity> selectByExample(UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    UserActivity selectByPrimaryKey(Integer activityid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserActivity record, @Param("example") UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByExample(@Param("record") UserActivity record, @Param("example") UserActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKeySelective(UserActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_activity
     *
     * @mbggenerated Thu Jul 19 15:40:10 CST 2018
     */
    int updateByPrimaryKey(UserActivity record);
}